package responses

type Item struct {
	D struct {
		Results []struct {
			Metadata struct {
				ID   string `json:"id"`
				URI  string `json:"uri"`
				Type string `json:"type"`
			} `json:"__metadata"`
			CompanyCode                    string      `json:"CompanyCode"`
			FiscalYear                     string      `json:"FiscalYear"`
			AccountingDocument             string      `json:"AccountingDocument"`
			AccountingDocumentItem         string      `json:"AccountingDocumentItem"`
			CompanyCodeName                string      `json:"CompanyCodeName"`
			ChartOfAccounts                string      `json:"ChartOfAccounts"`
			AccountingDocumentItemType     string      `json:"AccountingDocumentItemType"`
			ClearingDate                   string      `json:"ClearingDate"`
			ClearingCreationDate           string      `json:"ClearingCreationDate"`
			ClearingAccountingDocument     string      `json:"ClearingAccountingDocument"`
			IsCleared                      bool        `json:"IsCleared"`
			PostingKey                     string      `json:"PostingKey"`
			FinancialAccountType           string      `json:"FinancialAccountType"`
			SpecialGLCode                  string      `json:"SpecialGLCode"`
			SpecialGLTransactionType       string      `json:"SpecialGLTransactionType"`
			DebitCreditCode                string      `json:"DebitCreditCode"`
			BusinessArea                   string      `json:"BusinessArea"`
			BusinessAreaName               string      `json:"BusinessAreaName"`
			PartnerBusinessArea            string      `json:"PartnerBusinessArea"`
			TaxCode                        string      `json:"TaxCode"`
			WithholdingTaxCode             string      `json:"WithholdingTaxCode"`
			TaxType                        string      `json:"TaxType"`
			TransactionTypeDetermination   string      `json:"TransactionTypeDetermination"`
			ValueDate                      string      `json:"ValueDate"`
			AssignmentReference            string      `json:"AssignmentReference"`
			DocumentItemText               string      `json:"DocumentItemText"`
			PartnerCompany                 string      `json:"PartnerCompany"`
			FinancialTransactionType       string      `json:"FinancialTransactionType"`
			CorporateGroupAccount          string      `json:"CorporateGroupAccount"`
			PlanningLevel                  string      `json:"PlanningLevel"`
			ControllingArea                string      `json:"ControllingArea"`
			ControllingAreaName            string      `json:"ControllingAreaName"`
			CostCenter                     string      `json:"CostCenter"`
			CostCenterName                 string      `json:"CostCenterName"`
			Project                        string      `json:"Project"`
			OrderID                        string      `json:"OrderID"`
			BillingDocument                string      `json:"BillingDocument"`
			SalesDocument                  string      `json:"SalesDocument"`
			SalesDocumentItem              string      `json:"SalesDocumentItem"`
			ScheduleLine                   string      `json:"ScheduleLine"`
			MasterFixedAsset               string      `json:"MasterFixedAsset"`
			FixedAsset                     string      `json:"FixedAsset"`
			AssetTransactionType           string      `json:"AssetTransactionType"`
			AssetValueDate                 string      `json:"AssetValueDate"`
			PersonnelNumber                string      `json:"PersonnelNumber"`
			IsSalesRelated                 bool        `json:"IsSalesRelated"`
			LineItemDisplayIsEnabled       bool        `json:"LineItemDisplayIsEnabled"`
			IsOpenItemManaged              string      `json:"IsOpenItemManaged"`
			IsNotCashDiscountLiable        bool        `json:"IsNotCashDiscountLiable"`
			IsAutomaticallyCreated         bool        `json:"IsAutomaticallyCreated"`
			IsUsedInPaymentTransaction     bool        `json:"IsUsedInPaymentTransaction"`
			OperationalGLAccount           string      `json:"OperationalGLAccount"`
			GLAccount                      string      `json:"GLAccount"`
			GLAccountName                  string      `json:"GLAccountName"`
			GLAccountLongName              string      `json:"GLAccountLongName"`
			Customer                       string      `json:"Customer"`
			CustomerName                   string      `json:"CustomerName"`
			Supplier                       string      `json:"Supplier"`
			SupplierName                   string      `json:"SupplierName"`
			BranchAccount                  string      `json:"BranchAccount"`
			IsBalanceSheetAccount          bool        `json:"IsBalanceSheetAccount"`
			ProfitLossAccountType          string      `json:"ProfitLossAccountType"`
			SpecialGLAccountAssignment     string      `json:"SpecialGLAccountAssignment"`
			DueCalculationBaseDate         string      `json:"DueCalculationBaseDate"`
			PaymentTerms                   string      `json:"PaymentTerms"`
			CashDiscount1Days              string      `json:"CashDiscount1Days"`
			CashDiscount2Days              string      `json:"CashDiscount2Days"`
			NetPaymentDays                 string      `json:"NetPaymentDays"`
			CashDiscount1Percent           string      `json:"CashDiscount1Percent"`
			CashDiscount2Percent           string      `json:"CashDiscount2Percent"`
			PaymentMethod                  string      `json:"PaymentMethod"`
			PaymentBlockingReason          string      `json:"PaymentBlockingReason"`
			FixedCashDiscount              string      `json:"FixedCashDiscount"`
			HouseBank                      string      `json:"HouseBank"`
			BPBankAccountInternalID        string      `json:"BPBankAccountInternalID"`
			TaxDistributionCode1           string      `json:"TaxDistributionCode1"`
			TaxDistributionCode2           string      `json:"TaxDistributionCode2"`
			TaxDistributionCode3           string      `json:"TaxDistributionCode3"`
			InvoiceReference               string      `json:"InvoiceReference"`
			InvoiceReferenceFiscalYear     string      `json:"InvoiceReferenceFiscalYear"`
			InvoiceItemReference           string      `json:"InvoiceItemReference"`
			FollowOnDocumentType           string      `json:"FollowOnDocumentType"`
			StateCentralBankPaymentReason  string      `json:"StateCentralBankPaymentReason"`
			SupplyingCountry               string      `json:"SupplyingCountry"`
			InvoiceList                    string      `json:"InvoiceList"`
			BillOfExchangeUsage            string      `json:"BillOfExchangeUsage"`
			DunningKey                     string      `json:"DunningKey"`
			DunningBlockingReason          string      `json:"DunningBlockingReason"`
			LastDunningDate                string      `json:"LastDunningDate"`
			DunningLevel                   string      `json:"DunningLevel"`
			DunningArea                    string      `json:"DunningArea"`
			WithholdingTaxCertificate      string      `json:"WithholdingTaxCertificate"`
			Material                       string      `json:"Material"`
			Product                        string      `json:"Product"`
			Plant                          string      `json:"Plant"`
			PurchasingDocument             string      `json:"PurchasingDocument"`
			PurchasingDocumentItem         string      `json:"PurchasingDocumentItem"`
			AccountAssignmentNumber        string      `json:"AccountAssignmentNumber"`
			IsCompletelyDelivered          bool        `json:"IsCompletelyDelivered"`
			MaterialPriceControl           string      `json:"MaterialPriceControl"`
			ValuationArea                  string      `json:"ValuationArea"`
			InventoryValuationType         string      `json:"InventoryValuationType"`
			VATRegistration                string      `json:"VATRegistration"`
			DelivOfGoodsDestCountry        string      `json:"DelivOfGoodsDestCountry"`
			PaymentDifferenceReason        string      `json:"PaymentDifferenceReason"`
			ProfitCenter                   string      `json:"ProfitCenter"`
			ProfitCenterName               string      `json:"ProfitCenterName"`
			JointVenture                   string      `json:"JointVenture"`
			JointVentureCostRecoveryCode   string      `json:"JointVentureCostRecoveryCode"`
			JointVentureEquityGroup        string      `json:"JointVentureEquityGroup"`
			TreasuryContractType           string      `json:"TreasuryContractType"`
			AssetContract                  string      `json:"AssetContract"`
			CashFlowType                   string      `json:"CashFlowType"`
			TaxJurisdiction                string      `json:"TaxJurisdiction"`
			RealEstateObject               string      `json:"RealEstateObject"`
			SettlementReferenceDate        string      `json:"SettlementReferenceDate"`
			CommitmentItem                 string      `json:"CommitmentItem"`
			CostObject                     string      `json:"CostObject"`
			ProjectNetwork                 string      `json:"ProjectNetwork"`
			OrderInternalBillOfOperations  string      `json:"OrderInternalBillOfOperations"`
			OrderIntBillOfOperationsItem   string      `json:"OrderIntBillOfOperationsItem"`
			WBSElementInternalID           string      `json:"WBSElementInternalID"`
			ProfitabilitySegment           string      `json:"ProfitabilitySegment"`
			JointVentureEquityType         string      `json:"JointVentureEquityType"`
			IsEUTriangularDeal             bool        `json:"IsEUTriangularDeal"`
			CostOriginGroup                string      `json:"CostOriginGroup"`
			CompanyCodeCurrencyDetnMethod  string      `json:"CompanyCodeCurrencyDetnMethod"`
			ClearingIsReversed             bool        `json:"ClearingIsReversed"`
			PaymentMethodSupplement        string      `json:"PaymentMethodSupplement"`
			AlternativeGLAccount           string      `json:"AlternativeGLAccount"`
			FundsCenter                    string      `json:"FundsCenter"`
			Fund                           string      `json:"Fund"`
			PartnerProfitCenter            string      `json:"PartnerProfitCenter"`
			Reference1IDByBusinessPartner  string      `json:"Reference1IDByBusinessPartner"`
			Reference2IDByBusinessPartner  string      `json:"Reference2IDByBusinessPartner"`
			IsNegativePosting              bool        `json:"IsNegativePosting"`
			PaymentCardItem                string      `json:"PaymentCardItem"`
			PaymentCardPaymentSettlement   string      `json:"PaymentCardPaymentSettlement"`
			CreditControlArea              string      `json:"CreditControlArea"`
			Reference3IDByBusinessPartner  string      `json:"Reference3IDByBusinessPartner"`
			DataExchangeInstruction1       string      `json:"DataExchangeInstruction1"`
			DataExchangeInstruction2       string      `json:"DataExchangeInstruction2"`
			DataExchangeInstruction3       string      `json:"DataExchangeInstruction3"`
			DataExchangeInstruction4       string      `json:"DataExchangeInstruction4"`
			Region                         string      `json:"Region"`
			HasPaymentOrder                bool        `json:"HasPaymentOrder"`
			PaymentReference               string      `json:"PaymentReference"`
			TaxDeterminationDate           string      `json:"TaxDeterminationDate"`
			ClearingItem                   string      `json:"ClearingItem"`
			BusinessPlace                  string      `json:"BusinessPlace"`
			TaxSection                     string      `json:"TaxSection"`
			CostCtrActivityType            string      `json:"CostCtrActivityType"`
			AccountsReceivableIsPledged    string      `json:"AccountsReceivableIsPledged"`
			BusinessProcess                string      `json:"BusinessProcess"`
			GrantID                        string      `json:"GrantID"`
			FunctionalArea                 string      `json:"FunctionalArea"`
			FunctionalAreaName             string      `json:"FunctionalAreaName"`
			CustomerIsInExecution          bool        `json:"CustomerIsInExecution"`
			FundedProgram                  string      `json:"FundedProgram"`
			ClearingDocFiscalYear          string      `json:"ClearingDocFiscalYear"`
			LedgerGLLineItem               string      `json:"LedgerGLLineItem"`
			Segment                        string      `json:"Segment"`
			SegmentName                    string      `json:"SegmentName"`
			PartnerSegment                 string      `json:"PartnerSegment"`
			PartnerFunctionalArea          string      `json:"PartnerFunctionalArea"`
			HouseBankAccount               string      `json:"HouseBankAccount"`
			CostElement                    string      `json:"CostElement"`
			SEPAMandate                    string      `json:"SEPAMandate"`
			ReferenceDocumentType          string      `json:"ReferenceDocumentType"`
			OriginalReferenceDocument      string      `json:"OriginalReferenceDocument"`
			ReferenceDocumentLogicalSystem string      `json:"ReferenceDocumentLogicalSystem"`
			AccountingDocumentItemRef      string      `json:"AccountingDocumentItemRef"`
			FiscalPeriod                   string      `json:"FiscalPeriod"`
			AccountingDocumentCategory     string      `json:"AccountingDocumentCategory"`
			AccountingDocumentCategoryName string      `json:"AccountingDocumentCategoryName"`
			PostingDate                    string      `json:"PostingDate"`
			DocumentDate                   string      `json:"DocumentDate"`
			AccountingDocumentType         string      `json:"AccountingDocumentType"`
			AccountingDocumentTypeName     string      `json:"AccountingDocumentTypeName"`
			NetDueDate                     string      `json:"NetDueDate"`
			CashDiscount1DueDate           string      `json:"CashDiscount1DueDate"`
			CashDiscount2DueDate           string      `json:"CashDiscount2DueDate"`
			OffsettingAccount              string      `json:"OffsettingAccount"`
			OffsettingAccountType          string      `json:"OffsettingAccountType"`
			PartnerFund                    string      `json:"PartnerFund"`
			PartnerGrant                   string      `json:"PartnerGrant"`
			BudgetPeriod                   string      `json:"BudgetPeriod"`
			PartnerBudgetPeriod            string      `json:"PartnerBudgetPeriod"`
			BranchCode                     string      `json:"BranchCode"`
			CompanyCodeCurrency            string      `json:"CompanyCodeCurrency"`
			AmountInCompanyCodeCurrency    string      `json:"AmountInCompanyCodeCurrency"`
			TaxAmountInCoCodeCrcy          string      `json:"TaxAmountInCoCodeCrcy"`
			TaxBaseAmountInCoCodeCrcy      string      `json:"TaxBaseAmountInCoCodeCrcy"`
			ValuationDiffAmtInCoCodeCrcy   string      `json:"ValuationDiffAmtInCoCodeCrcy"`
			CashDiscountAmtInCoCodeCrcy    string      `json:"CashDiscountAmtInCoCodeCrcy"`
			InvoiceAmtInCoCodeCrcy         string      `json:"InvoiceAmtInCoCodeCrcy"`
			TransactionCurrency            string      `json:"TransactionCurrency"`
			AmountInTransactionCurrency    string      `json:"AmountInTransactionCurrency"`
			OriginalTaxBaseAmount          string      `json:"OriginalTaxBaseAmount"`
			TaxAmount                      string      `json:"TaxAmount"`
			TaxBaseAmountInTransCrcy       string      `json:"TaxBaseAmountInTransCrcy"`
			WithholdingTaxBaseAmount       string      `json:"WithholdingTaxBaseAmount"`
			PlannedAmtInTransactionCrcy    string      `json:"PlannedAmtInTransactionCrcy"`
			CashDiscountBaseAmount         string      `json:"CashDiscountBaseAmount"`
			CashDiscountAmount             string      `json:"CashDiscountAmount"`
			NetPaymentAmount               string      `json:"NetPaymentAmount"`
			WithholdingTaxAmount           string      `json:"WithholdingTaxAmount"`
			WithholdingTaxExemptionAmt     string      `json:"WithholdingTaxExemptionAmt"`
			InvoiceAmountInFrgnCurrency    string      `json:"InvoiceAmountInFrgnCurrency"`
			BalanceTransactionCurrency     string      `json:"BalanceTransactionCurrency"`
			AmountInBalanceTransacCrcy     string      `json:"AmountInBalanceTransacCrcy"`
			AdditionalCurrency1            string      `json:"AdditionalCurrency1"`
			ValuationDiffAmtInAddlCrcy1    string      `json:"ValuationDiffAmtInAddlCrcy1"`
			AmountInAdditionalCurrency1    string      `json:"AmountInAdditionalCurrency1"`
			AdditionalCurrency2            string      `json:"AdditionalCurrency2"`
			AmountInAdditionalCurrency2    string      `json:"AmountInAdditionalCurrency2"`
			ValuationDiffAmtInAddlCrcy2    string      `json:"ValuationDiffAmtInAddlCrcy2"`
			PaymentCurrency                string      `json:"PaymentCurrency"`
			AmountInPaymentCurrency        string      `json:"AmountInPaymentCurrency"`
			CreditControlAreaCurrency      string      `json:"CreditControlAreaCurrency"`
			HedgedAmount                   string      `json:"HedgedAmount"`
			BaseUnit                       string      `json:"BaseUnit"`
			Quantity                       string      `json:"Quantity"`
			GoodsMovementEntryUnit         string      `json:"GoodsMovementEntryUnit"`
			QuantityInEntryUnit            string      `json:"QuantityInEntryUnit"`
			PurchasingDocumentPriceUnit    string      `json:"PurchasingDocumentPriceUnit"`
			PurchaseOrderQty               string      `json:"PurchaseOrderQty"`
			MaterialPriceUnitQty           string      `json:"MaterialPriceUnitQty"`
			NumberOfItems                  string      `json:"NumberOfItems"`
			AccountingDocumentCreationDate string      `json:"AccountingDocumentCreationDate"`
			CreationTime                   string      `json:"CreationTime"`
			LastChangeDate                 string      `json:"LastChangeDate"`
			ExchangeRateDate               string      `json:"ExchangeRateDate"`
			AccountingDocCreatedByUser     string      `json:"AccountingDocCreatedByUser"`
			TransactionCode                string      `json:"TransactionCode"`
			IntercompanyTransaction        string      `json:"IntercompanyTransaction"`
			DocumentReferenceID            string      `json:"DocumentReferenceID"`
			RecurringAccountingDocument    string      `json:"RecurringAccountingDocument"`
			ReverseDocument                string      `json:"ReverseDocument"`
			ReverseDocumentFiscalYear      string      `json:"ReverseDocumentFiscalYear"`
			AccountingDocumentHeaderText   string      `json:"AccountingDocumentHeaderText"`
			ExchangeRate                   string      `json:"ExchangeRate"`
			BusinessTransactionType        string      `json:"BusinessTransactionType"`
			BatchInputSession              string      `json:"BatchInputSession"`
			FinancialManagementArea        string      `json:"FinancialManagementArea"`
			ReversalIsPlanned              bool        `json:"ReversalIsPlanned"`
			PlannedReversalDate            string      `json:"PlannedReversalDate"`
			TaxIsCalculatedAutomatically   bool        `json:"TaxIsCalculatedAutomatically"`
			TaxBaseAmountIsNetAmount       bool        `json:"TaxBaseAmountIsNetAmount"`
			SourceCompanyCode              string      `json:"SourceCompanyCode"`
			LogicalSystem                  string      `json:"LogicalSystem"`
			TaxExchangeRate                string      `json:"TaxExchangeRate"`
			ReversalReason                 string      `json:"ReversalReason"`
			Branch                         string      `json:"Branch"`
			Reference1InDocumentHeader     string      `json:"Reference1InDocumentHeader"`
			Reference2InDocumentHeader     string      `json:"Reference2InDocumentHeader"`
			InvoiceReceiptDate             string      `json:"InvoiceReceiptDate"`
			Ledger                         string      `json:"Ledger"`
			LedgerGroup                    string      `json:"LedgerGroup"`
			AlternativeReferenceDocument   string      `json:"AlternativeReferenceDocument"`
			TaxReportingDate               string      `json:"TaxReportingDate"`
			AccountingDocumentClass        string      `json:"AccountingDocumentClass"`
			ExchangeRateType               string      `json:"ExchangeRateType"`
			LatePaymentReason              string      `json:"LatePaymentReason"`
			SalesDocumentCondition         string      `json:"SalesDocumentCondition"`
			IsReversal                     bool        `json:"IsReversal"`
			IsReversed                     bool        `json:"IsReversed"`
		} `json:"results"`
	} `json:"d"`
}
